cc_test(
    name = "oracle_check",
    srcs = ["oracle_check.cc"],
    deps = [
        "@com_google_absl//absl/numeric:int128",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/types:span",
        "@distributed_point_functions//dpf:distributed_point_function",
        "@distributed_point_functions//dpf:int_mod_n",
    ],
)
